
# Singleton service factory configuration/IoC injection
singletons:

  - com.networknt.decrypt.Decryptor:
      - com.networknt.decrypt.AESDecryptor
  - com.networknt.db.H2DataSource:
      - com.networknt.db.H2DataSource:
          - java.lang.String: H2DataSource
  - com.mservicetech.campsite.repository.ApiSqlSessionFactoryBuilder:
      - com.mservicetech.campsite.repository.ApiSqlSessionFactoryBuilder
  - com.mservicetech.campsite.repository.CampsiteRepository:
      - com.mservicetech.campsite.repository.CampsiteRepositoryJdbcImpl
  - com.mservicetech.campsite.service.CampsiteService:
      - com.mservicetech.campsite.service.CampsiteServiceImpl

  # StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
    - com.mservicetech.campsite.H2DatasourceStartupHook
  
  # ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.ShutdownHookProvider:

  



